# Generated by Django 5.2.4 on 2025-10-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_articulo', models.CharField(max_length=50, unique=True)),
                ('unidades_contenedor', models.PositiveIntegerField()),
                ('unidades_cbm', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100, unique=True)),
                ('flete_ipl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flete_blue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flete_directo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
