# Generated by Django 5.2.4 on 2025-10-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulo',
            new_name='Unidades',
        ),
    ]
