# Generated by Django 5.2.4 on 2025-11-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factores', '0002_rename_articulo_unidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('SV', 'El Salvador'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('CR', 'Costa Rica'), ('PA', 'Panamá')], max_length=2, unique=True)),
                ('almacenaje', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('honorarios_aduanales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inspeccion_intrusiva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custodio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flete_internacional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inspeccion_calidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costos_documentacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('planilla_asia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flete_local', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
