# Generated by Django 5.2.4 on 2025-11-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factores', '0003_costopais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costopais',
            name='flete_internacional',
        ),
        migrations.RemoveField(
            model_name='costopais',
            name='planilla_asia',
        ),
    ]
