# Generated by Django 5.2.4 on 2025-11-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factores', '0004_remove_costopais_flete_internacional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costopais',
            name='pais',
            field=models.CharField(choices=[('SV', 'El Salvador'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('CR', 'Costa Rica'), ('PA', 'Panamá'), ('NI', 'Nicaragua')], max_length=2, unique=True),
        ),
    ]
