# Generated by Django 5.2.4 on 2025-11-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factores', '0005_alter_costopais_pais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costopais',
            old_name='costos_documentacion',
            new_name='flete_terrestre_ca',
        ),
        migrations.RenameField(
            model_name='costopais',
            old_name='inspeccion_calidad',
            new_name='inspeccion_no_intrusiva',
        ),
        migrations.RemoveField(
            model_name='costopais',
            name='inspeccion_intrusiva',
        ),
    ]
