# Generated by Django 5.2.4 on 2025-11-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factores', '0006_rename_costos_documentacion_costopais_flete_terrestre_ca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flete',
            name='flete_luno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
