# Generated by Django 5.2.4 on 2025-12-02 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factores', '0007_flete_flete_luno'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factores.costtype')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factores.country')),
            ],
        ),
        migrations.CreateModel(
            name='TariffTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CostoPais',
        ),
        migrations.AddField(
            model_name='tariff',
            name='tariff_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factores.tarifftable'),
        ),
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together={('tariff_table', 'country', 'cost_type')},
        ),
    ]
