# Generated by Django 5.2.4 on 2025-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factores', '0008_costtype_country_tariff_tarifftable_delete_costopais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='export_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='import_country',
            field=models.BooleanField(default=False),
        ),
    ]
