# Generated by Django 5.2.4 on 2025-09-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
                ('embarque', models.CharField(max_length=100)),
                ('expediente', models.CharField(max_length=50, unique=True)),
                ('tamano', models.CharField(max_length=20)),
                ('fecha_pos', models.DateField()),
                ('fecha_despacho', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EN_TRANSITO', 'En tránsito'), ('VERIFICADO', 'Verificado'), ('ENTREGADO', 'Entregado')], max_length=50)),
                ('transporte', models.CharField(max_length=50)),
                ('eta', models.DateField()),
                ('dai', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fts', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
