# Generated by Django 5.2.4 on 2025-10-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='dai',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='eta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='fecha_pos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='fts',
            field=models.CharField(max_length=40),
        ),
    ]
