# Generated by Django 5.2.4 on 2025-10-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_description', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('origen', models.TextField()),
            ],
        ),
    ]
